[project]
name = "learning-trl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.6.0",
    "datasets>=3.5.0",
    "pillow>=11.2.1",
    "torch>=2.7.0",
    "transformers>=4.51.3",
    "trl>=0.17.0",
]
